### ISSUE TITLE
Json error while executing

### ISSUE THREAD

**Issue by Lifter** [twilio/twilio-php#188]
Hi, twilio. 

I have strange error when executing a code of library(creating Services_Twilio or updating a call): 
[25-Aug-2014 04:03:44] PHP Warning:  file_get_contents(./users_1/3001.txt): failed to open stream: No such file or directory in /var/www/html/bluebox/attend-transfer/dial.php on line 7
[25-Aug-2014 04:03:44] PHP Notice:  Undefined offset: 1 in /var/www/html/bluebox/attend-transfer/dial.php on line 9
[25-Aug-2014 04:03:44] PHP Notice:  Undefined offset: 2 in /var/www/html/bluebox/attend-transfer/dial.php on line 9
[25-Aug-2014 04:03:44] PHP Notice:  Undefined offset: 1 in /var/www/html/bluebox/attend-transfer/dial.php on line 10
[25-Aug-2014 04:03:47] PHP Notice:  Undefined offset: 1 in /usr/share/twilio/Services/Twilio/TinyHttp.php on line 91
[25-Aug-2014 04:03:47] PHP Notice:  Undefined offset: 1 in /usr/share/twilio/Services/Twilio/TinyHttp.php on line 102
[25-Aug-2014 04:03:47] PHP Notice:  Undefined offset: 1 in /usr/share/twilio/Services/Twilio/TinyHttp.php on line 102
[25-Aug-2014 04:03:47] PHP Notice:  Undefined offset: 1 in /usr/share/twilio/Services/Twilio/TinyHttp.php on line 102
[25-Aug-2014 04:03:47] PHP Notice:  Undefined offset: 1 in /usr/share/twilio/Services/Twilio/TinyHttp.php on line 102
[25-Aug-2014 04:03:47] PHP Notice:  Undefined offset: 1 in /usr/share/twilio/Services/Twilio/TinyHttp.php on line 102
[25-Aug-2014 04:03:47] PHP Notice:  Undefined offset: 1 in /usr/share/twilio/Services/Twilio/TinyHttp.php on line 102
[25-Aug-2014 04:03:47] PHP Notice:  Undefined offset: 1 in /usr/share/twilio/Services/Twilio/TinyHttp.php on line 102
[25-Aug-2014 04:03:47] PHP Fatal error:  Uncaught exception 'Services_Twilio_RestException' with message 'Could not decode response body as JSON. This likely indicates a 500 server error' in /usr/share/twilio/Services/Twilio.php:295
Stack trace:
#0 /usr/share/twilio/Services/Twilio.php(229): Services_Twilio->_processResponse(Array)
#1 /usr/share/twilio/Services/Twilio/InstanceResource.php(31): Services_Twilio->createData('/2010-04-01/Acc...', Array)
#2 /var/www/html/bluebox/attend-transfer/dial.php(14): Services_Twilio_InstanceResource->update(Array)
#3 {main}

  thrown in /usr/share/twilio/Services/Twilio.php on line 295

Can you please provide me an advice why this can happen? Where folder 2010-04-01 is placed? 
Thank you beforehand.

**Comment by efossier** [comment]
We've completely rewritten the library for 5.x, please upgrade and let us know if this is still an issue.
