### ISSUE TITLE
Phone number lookup

### ISSUE THREAD

**Issue by bajke992** [twilio/twilio-php#403]
As of January 31st I started getting "Undefined index: caller_name" errors from the twilio/sdk package. The phone number lookup worked fine prior to January 31st.

**Version:**
**API Subdomain (lookups):**

### Code Snippet
Use:
```php
public function handle(QueueSmsEvent $event)
{
    $message = $event->message;
    if (env('APP_ENV') != 'local' && env('APP_ENV') != 'testing') {
        try {
            $client = new Client(env('TWILIO_ACCOUNT_SID'), env('TWILIO_AUTH_TOKEN'));
            $number = $client->lookups->phoneNumbers($event->account->mobile_phone)->fetch([
                'type' => 'carrier'
            ]); //QueueSmsEventListener.php(41)

            switch ($number->carrier['type']) {
                case 'landline' :
                    if ($event->account->home_phone) {
                        $event->account->other_phone  = $event->account->mobile_phone;
                        $event->account->mobile_phone = null;
                    } else {
                        $event->account->home_phone = $event->account->mobile_phone;
                        $event->account->mobile_phone = null;
                    }
                    
                    $event->account->save();
                    return;
                    break;
                case 'voip' :
                    $event->account->other_phone  = $event->account->mobile_phone;
                    $event->account->mobile_phone = null;
                    $event->account->save();
                    return;
                    break;
                default :
                    break;
            }
        } catch (RestException $e) {
            if(str_contains($e->getMessage(), 'Unable to fetch record')){
                $event->account->mobile_phone = null;
                $event->account->save();
                return;
            }
        }

        $this->dispatch((new SmsJob($message)));
    }
}
```

### Response from API call
```json
{
  "caller_name": null,
  "country_code": "CA",
  "phone_number": "+15143168391",
  "national_format": "(514) 316-8391",
  "carrier": {
    "mobile_country_code": null,
    "mobile_network_code": null,
    "name": "Twilio",
    "type": "voip",
    "error_code": null
  },
  "add_ons": null,
  "url": "https://lookups.twilio.com/v1/PhoneNumbers/+15143168391?Type=carrier"
}
```

### Exception / Log
```json
"message": "Undefined index: caller_name",
"status_code": 500,
"debug": {
  "line": 39,
  "file": "/var/app/current/vendor/twilio/sdk/Twilio/Rest/Lookups/V1/PhoneNumberInstance.php",
  "class": "ErrorException",
  "trace": [
    "#0 /var/app/current/vendor/twilio/sdk/Twilio/Rest/Lookups/V1/PhoneNumberInstance.php(39): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/app/curren...', 39, Array)",
    "#1 /var/app/current/vendor/twilio/sdk/Twilio/Rest/Lookups/V1/PhoneNumberContext.php(62): Twilio\\Rest\\Lookups\\V1\\PhoneNumberInstance->__construct(Object(Twilio\\Rest\\Lookups\\V1), Array, NULL)",
    "#2 /var/app/current/app/Listeners/QueueSmsEventListener.php(41): Twilio\\Rest\\Lookups\\V1\\PhoneNumberContext->fetch(Object(Twilio\\Values))",
    "#3 [internal function]: App\\Listeners\\QueueSmsEventListener->handle(Object(App\\Events\\QueueSmsEvent))",
    "#4 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(354): call_user_func_array(Array, Array)",
    "#5 [internal function]: Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(Object(App\\Events\\QueueSmsEvent))",
    "#6 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)",
    "#7 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(478): Illuminate\\Events\\Dispatcher->fire('App\\\\Events\\\\Queu...')",
    "#8 /var/app/current/app/Models/Account.php(669): event(Object(App\\Events\\QueueSmsEvent))",
    "#9 /var/app/current/app/Http/Api/V1/Controllers/AccountController.php(213): App\\Models\\Account->sendVerificationSMS('+15143168391', 'update')",
    "#10 [internal function]: App\\Http\\Api\\V1\\Controllers\\AccountController->update(Object(App\\Http\\Api\\V1\\Requests\\UpdateAccountAPIRequest))",
    "#11 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)",
    "#12 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\\Routing\\Controller->callAction('update', Array)",
    "#13 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Api\\V1\\Controllers\\AccountController), 'update')",
    "#14 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\\Routing\\Route->runController()",
    "#15 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\\Routing\\Route->run(Object(Dingo\\Api\\Http\\Request))",
    "#16 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#17 /var/app/current/vendor/tymon/jwt-auth/src/Middleware/GetUserFromToken.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#18 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Tymon\\JWTAuth\\Middleware\\GetUserFromToken->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
    "#19 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#20 /var/app/current/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#21 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
    "#22 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#23 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#24 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
    "#25 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
    "#26 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
    "#27 /var/app/current/vendor/dingo/api/src/Routing/Adapter/Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
    "#28 /var/app/current/vendor/dingo/api/src/Routing/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
    "#29 /var/app/current/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
    "#30 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#31 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#32 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
    "#33 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
    "#34 /var/app/current/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
    "#35 /var/app/current/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
    "#36 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
    "#37 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "#38 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
    "#39 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
    "#40 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
    "#41 /var/app/current/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
    "#42 {main}"
  ]
}
```

### Steps to Reproduce
Perform this call with the php twilio/sdk package with any phone number:
```php
$client = new Client(env('TWILIO_ACCOUNT_SID'), env('TWILIO_AUTH_TOKEN'));
$number = $client->lookups->phoneNumbers($event->account->mobile_phone)->fetch([
    'type' => 'carrier'
]);
```

**Comment by jmctwilio** [comment]
@bajke992 Thanks for bringing this up.  I've just attempted to reproduce the exception and was unable to do so with the current version of the library.  As I believe this issue has been resolved, I'm closing this ticket.

I'm very sorry it took so long to get a response.  The team has been very busy updating the libraries to be automatically generated so we can more easily keep pace with Twilio's fast-growing feature set.  The code generation has helped correct a lot of issues like this as well.  If you experience any other problems, please feel free to submit a new issue or open a PR.  Thank you.
