### ISSUE TITLE
Class 'Twilio\Twiml' not found

### ISSUE THREAD

**Issue by mcpacific** [twilio/twilio-php#618]
### Issue Summary
Starting today I have had failures in my Laravel app. The log shows 'Class 'Twilio\Twiml' not found' errors. This happened before updating anything. However, I thought maybe updating the SDK would help (but it doesn't).

### Steps to Reproduce
1. Edit composer.json to require "twilio/sdk": "^6.1".
2. Ensure webhook is properly configured.
3. Call number assigned to webhook.
4. Observe error log.

### Code Snippet
```
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Twilio\Twiml;

class WhateverController extends Controller {
  
    /**
     * Responds with a welcome message with options
     *
     * @return \Illuminate\Http\Response
     */
    public function showWelcome(Request $request ) {
      
      $from = $request->input('From');
      $response = new Twiml();

      $gather = $response->gather(
          ['numDigits' => 1,
           'action' => route('main-menu', [], false),
           'method' => 'GET']
      );

      $gather->play(
          '/assets/prompts/main-menu.wav',
          ['loop' => 2]
      );
        
      return $response;
    }
  
}
```

### Exception/Log
```
[2020-03-19 16:03:39] local.ERROR: Class 'Twilio\Twiml' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Twilio\\Twiml' not found at /beta/app/Http/Controllers/WhateverController.php:26)
[stacktrace]
#0 [internal function]: App\\Http\\Controllers\\WhateverController->showWelcome(Object(Illuminate\\Http\\Request), Object(Twilio\\Rest\\Client))
#1 /beta/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#2 /beta/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('showWelcome', Array)
#3 /beta/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\WhateverController), 'showWelcome')
#4 /beta/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#5 /beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#6 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /beta/app/Http/Middleware/StarReturnMiddleware.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\StarReturnMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /beta/vendor/jacobbennett/laravel-http2serverpush/src/Middleware/AddHttp2ServerPush.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): JacobBennett\\Http2ServerPush\\Middleware\\AddHttp2ServerPush->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /beta/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /beta/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /beta/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /beta/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /beta/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /beta/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#37 /beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#38 /beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 /beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#40 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#41 /beta/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#58 /beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#59 /beta/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#60 {main}
"} 
```

### Technical details:
* twilio-php version: 6.1.0
* php version: 7.3.15

**Comment by mcpacific** [comment]
After reading the updated documentation I made the following changes to the code:
```
...
use Twilio\TwimML\VoiceResponse;

class WhateverController extends Controller {

    public function showWelcome(Request $request ) {
      ...
      $response = new VoiceResponse();
      ...
}
```

However, now I'm receiving a 12100 error, as an extra <head/> tag is being inserted at the beginning of the xml as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<head/>
<Response>
    <Gather numDigits="1" action="/ivr/main-menu" method="GET">
        <Play loop="2">/assets/prompts/main-menu.wav</Play>
    </Gather>
</Response>
```

I printed out the response before returning to Twilio and there is no <head/> tag in $response before the return:

```
<?xml version="1.0" encoding="UTF-8"?>
<Response><Gather numDigits="1" action="/ivr/main-menu" method="GET"><Play loop="2">/assets/prompts/main-menu.wav</Play></Gather></Response>
```

**Comment by childish-sambino** [comment]
Hmm, sounds similar to this question: https://stackoverflow.com/questions/46610733/why-is-blade-making-a-head-tag

I don't think this is an issue with the TwiML generation in this lib. Does the link above help out?

**Comment by mcpacific** [comment]
No this doesn't help. There is no view being rendered so no HTML being generated. The function merely produces XML and returns it to Twilio. Also, please note the incorrectly formed single tag '\<head\/>'. Head tags are normally not self-closing and come in pairs (ie. \<head\>...\<\/head\>). If I change the code to just say 'hello' like this it produces the same error:

```
...
use Twilio\TwimML\VoiceResponse;

class WhateverController extends Controller {

    public function showWelcome(Request $request ) {
      ...
      $response = new VoiceResponse();
      $response->say('hello');

      return $response;
}
```

**Comment by childish-sambino** [comment]
Do you have any middleware configured to run post-processing on the response?

**Comment by mcpacific** [comment]
No.

**Comment by childish-sambino** [comment]
Best to [file a support ticket](https://twilio.com/help/contact) then to see if anything is happening on the back-end.

**Comment by mcpacific** [comment]
> Best to [file a support ticket](https://twilio.com/help/contact) then to see if anything is happening on the back-end.

I did that yesterday but so far they have been unable to come up with a relevant response.

**Comment by childish-sambino** [comment]
What about narrowing this down. If you hit your endpoint with something like cURL or Postman, do you still get the `head` tag?

**Comment by mcpacific** [comment]
> What about narrowing this down. If you hit your endpoint with something like cURL or Postman, do you still get the `head` tag?

Indeed. Thankfully I ended up using cURL on the console to inspect the response headers earlier today. Sure enough, the \<head\/\> tag was being inserted by my server. This led me to another post that mentioned explicitly setting the Content-Type header as 'application/xml'. First, I tested that specific function:

```
return response( $response )->header( 'Content-Type', 'application/xml' );
```
and it worked like a charm. I imaging that the latest update of twilio-php now requires TwiML responses to include Content-Type explicitly in the header. So my original issue was resolved. 

I guess this is not a bug, but perhaps someone else will stumble across this and find this information helpful. Later, I thought about your comment about Middleware; I ended up grouping all my routes that generate TwiML and created a Middleware to handle the xml headers (I did it more as an exercise, since it doesn't really matter which way the headers are applied).

After all this I thought I was home free, but I also started getting additional errors, such as
```
HP Fatal error:  Method Twilio\TwiML\VoiceResponse::__toString() must not throw an exception, caught ErrorException: Trying to get property 'name' of non-object in /vendor/symfony/http-foundation/Response.php on line 0
```
https://github.com/twilio/twilio-php/issues/546 was very helpful in resolving a Taskrouter issue I was having. Similarly, elsewhere in my code I had a hard time getting my Dial verb to work with a Client noun. I guess the 'name' property is now required in this case, so I used 'null' in my code to resolve this:

```
    $response = new VoiceResponse();
    $response->play( '/assets/prompts/greetings.mp3' );
    $dialCommand = $response->dial( null, [
      'record' => 'record-from-answer',
      'recordingStatusCallback' => route('store-recordings', [
        'user_id' => $systemUserId,
        'monitored_ext' => $user->extension,
      ], false ),
      'action' => route( 'user-voicemail', [ 'user_id' => $user->id ], false )
    ]);
    $dialCommand->client($clientToDial);
```
