### ISSUE TITLE
[6.15.1] Conversations Attributes not valid JSON error

### ISSUE THREAD

**Issue by passionInfinite** [twilio/twilio-php#672]
### Issue Summary
I tried creating Conversation User with the following request and payload. It says Invalid Attribute JSON for attributes parameters I double checked it I am using php and to pass json as string we need to use `json_encode`. In addition to that I tested the output of my json_encoded string and tested it on jsonlint.com and it was valid JSON.

### Steps to Reproduce
1. Use Twilio SDK 6.15.1
2. Use the below snippet that uses the SDK to call and create conversations user.
3. The request will fail with the below given exception.

### Code Snippet
```php
$user = $this->twilio()->conversations->v1->users->create('5fe0cdcb92497630821fc242', [
'friendlyName' => 'Hardik Patel',
'attributes' => json_encode([ 'profileUrl' => 'https://www.gravatar.com/avatar/a090daa25330a1e0ba5d0001fd5471e6?d=identicon' ], JSON_FORCE_OBJECT)
]); 
```

### Exception/Log
```
[HTTP 400] Unable to create record: Attributes not valid JSON {"exception":"[object] (Twilio\\Exceptions\\RestException(code: 50304): [HTTP 400] Unable to create record: Attributes not valid JSON at /api-v2/vendor/twilio/sdk/src/Twilio/Version.php:88)
[stacktrace]
#0 /api-v2/vendor/twilio/sdk/src/Twilio/Version.php(223): Twilio\\Version->exception()
#1 /api-v2/vendor/twilio/sdk/src/Twilio/Rest/Conversations/V1/UserList.php(53): Twilio\\Version->create()
#2 /api-v2/app/Core/Twilio/Traits/ManagesIdentities.php(37): Twilio\\Rest\\Conversations\\V1\\UserList->create()
```

After asking help from Twilio Support. They provided steps to debug the request. The debug output can be found below.

```
*   Trying 52.2.204.41:443...
* Connected to conversations.twilio.com (52.2.204.41) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /usr/local/etc/openssl@1.1/cert.pem
*  CApath: /usr/local/etc/openssl@1.1/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Twilio, Inc.; CN=*.twilio.com
*  start date: Mar 30 00:00:00 2020 GMT
*  expire date: Mar 30 12:00:00 2021 GMT
*  subjectAltName: host "conversations.twilio.com" matched cert's "*.twilio.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=Thawte RSA CA 2018
*  SSL certificate verify ok.
> POST /v1/Users HTTP/1.1
Host: conversations.twilio.com
User-Agent: twilio-php/6.15.1 (PHP 7.4.13)
Accept-Charset: utf-8
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: Basic AUTH_TOKEN
Content-Length: 209

* upload completely sent off: 209 out of 209 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 BAD REQUEST
< Date: Mon, 21 Dec 2020 16:14:35 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 127
< Connection: keep-alive
< Twilio-Request-Id: RQe123f5b3cd844b1e9cd1b58824aa3d4b
< Twilio-Request-Duration: 0.054
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
< Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS
< Access-Control-Expose-Headers: ETag
< Access-Control-Allow-Credentials: true
< X-Powered-By: AT-5000
< X-Shenanigans: none
< X-Home-Region: us1
< X-API-Domain: conversations.twilio.com
< Strict-Transport-Security: max-age=31536000
< 
* Connection #0 to host conversations.twilio.com left intact
```

I was also able to dig deeper, the following is the buidQuery output for the data of the request. Also when urldecoded the Attributes part is valid json.

```
"Identity=5fe0cdcb92497630821fc242&FriendlyName=Hardik+Patel&Attributes=%7B%22profileUrl%22%3A%22https%3A%5C%2F%5C%2Fwww.gravatar.com%5C%2Favatar%5C%2Fa090daa25330a1e0ba5d0001fd5471e6%3Fd%3Didenticon%22%7D"
```

### Technical details:
* twilio-php version: 6.15.1
* php version: 7.4

**Comment by thinkingserious** [comment]
Hello @passionInfinite,

Can you please try the [call](https://www.twilio.com/docs/conversations/quickstart) with using `json_encode`? 

Thanks!

With best regards,

Elmer
